spring.application.name=autotrackspringboot
server.port=8082

# Mail Configuration (Update with your actual Gmail and App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anasretiwala10@gmail.com
spring.mail.password=tutmiovakwlwobrk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File upload constraints
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Enable automatic refresh for templates
spring.thymeleaf.cache=false